baseURL: /
theme: casper3
title: ETdoFresh
languageCode: en-us
params:
    dateFormat: Mon, Jan 2, 2006
    description: Laissez les bons programmations rouler!
    email: "etdofresh@gmail.com"
    facebook: https://facebook.com/etdofresh
    github: https://github.com/etdofresh
    twitter: https://twitter.com/etdofresh
    headline: My headline
    intro: true
    logo: /images/2020/07/ETdoFresh-1.png
    mainSections: ["post"]
    opengraph: true
    shareTwitter: true

permalinks:
    post: /:filename/

googleAnalytics: UA-170496873-1

