baseURL = "/"
languageCode = "en-us"
title = "ETdoFresh"
theme = "casper3"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "Laissez les bons programmations rouler!"
    github = "https://github.com/etdofresh"
    twitter = "https://twitter.com/etdofresh"
	facebook = "https://facebook.com/etdofresh"
    email = "etdofresh@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
	logo = "/images/2020/07/ETdoFresh-1.png"

[Permalinks]
    post = "/:filename/"