baseURL: /
theme: casper3
title: ETdoFresh
languageCode: en-us
params:
    dateFormat: Mon, Jan 2, 2006
    description: Laissez les bons programmations rouler!
    email: "etdofresh@gmail.com"
    facebook: https://facebook.com/etdofresh
    github: https://github.com/etdofresh
    twitter: https://twitter.com/etdofresh
    headline: My headline
    intro: true
    logo: /images/2020/07/ETdoFresh-1.png
    mainSections: ["post"]
    opengraph: true
    shareTwitter: true

permalinks:
    post: /:filename/

taxonomies:
    author: author
    tag: tags

googleAnalytics: UA-170496873-1

menu:
    main:
      - identifier: projects
        name: Projects
        url: /tags/project/
        weight: 1
        
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 2
    