baseURL = "/"
languageCode = "en-us"
theme = "casper3"
title = "ETdoFresh"
[Params]
dateFormat = "Mon, Jan 2, 2006"
description = "Laissez les bons programmations rouler!"
email = "etdofresh@gmail.com"
facebook = "https://facebook.com/etdofresh"
github = "https://github.com/etdofresh"
headline = "My headline"
intro = true
logo = "/images/2020/07/ETdoFresh-1.png"
mainSections = ["post"]
opengraph = true
shareTwitter = true
twitter = "https://twitter.com/etdofresh"
[Permalinks]
post = "/:filename/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
