name: Hugo Build
on:
  push:
    branches:
    - master
jobs:
  windows:
    name: Hugo Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ETdoFresh/Actions/HugoBuild@latest
    - uses: ETdoFresh/Actions/UploadToGithubIO@latest
      with:
          GITHUB_IO_REPOSITORY: ETdoFresh/etdofresh.github.io
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
